version: "3.9"
services:
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/UNI-CHATBOT
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: ankane/pgvector
    container_name: my-postgres1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
